### ISSUE TITLE
table row click action

### ISSUE THREAD

**Issue by jasonmarshallc2** [jasonmarshallc2/Car#4]
When a table row is clicked, perform another action.  First is on the customer table, when clicked, show the jobs for that customer ID

**Comment by thejasonpettit** [comment]
Added rowClick support in latest commit: https://github.com/jasonmarshallc2/Mopeds/commit/b4a5f025dd8fe6b5ab8641bb143a7886a89a7a33
Working on the "show jobs" now

**Comment by jasonmarshallc2** [comment]
When I click a customer row, the customer information shows, but I don't see the jobs for that customer. The call should be to jobsByCustomer&custID=x  Am I missing something?

**Comment by thejasonpettit** [comment]
haha, yes! You're missing my latest changes, I'll get those up today

**Comment by thejasonpettit** [comment]
Jobs now in customer details 👍
