### ISSUE TITLE
Need a template for the scan js to live

### ISSUE THREAD

**Issue by jasonmarshallc2** [jasonmarshallc2/Car#5]
I'm still learning react and am struggling to get the scan page to show content. Please give me a hello world type of page for the scan navbar destination.  You should see Scan.js in the client folder, a copy of Customers.js gutted.  I did branch it to 1.1 for the merge.

**Comment by thejasonpettit** [comment]
Added React scan to 1.1 - "works on my box"
It sends a JSON object of the scanned data to `/api/tasks`, adjust as needed
